In [2]:
import numpy as np
a = np.arange(12)
a = a.reshape(3,4)
print(a)
a = a.flatten()
print(a)


# stacking
b = np.array([1,2,3])
c = np.array([4,5,6])

print(np.vstack((b,c)))
print(np.hstack((b,c)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


### random and statistics

In [8]:
a = np.random.rand(3)
print(a)
b = np.random.randn(3)
print(b)
c = np.random.randint(1,10,5)
print(c)

# statistics
a = np.array([1,2,3,4,5])
print(np.mean(a))
print(np.std(a))

[0.51550483 0.38815436 0.73999993]
[ 0.55410914  1.08385526 -0.64669568]
[1 7 2 1 4]
3.0
1.4142135623730951


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
np.where(arr>5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [4]:
import sys
py_arr = [0, 4, 55, 2]
np_arr = np.array(py_arr)

In [5]:
sys.getsizeof(1) * len(py_arr)  # size of the list in bytes

112

In [6]:
np_arr.itemsize * np_arr.size  # size of the numpy array in bytes 

32