# Numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.


                   Structure	Example

                      Scalar	5

                      Vector	1D [1,2,3]

                      Matrix	2D [[1,2],[3,4]]

                      Tensor	3D+ arrays


In [2]:
import numpy as np

#Create arrays using numpy
#Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
import numpy as np

# empty array
a = np.empty((2,3)) 
print(a)

# full array
b = np.full((2,2), 7)
print(b)

# random arrays
c = np.random.rand(2,3)  #Uniform Distribution
d = np.random.randint(1, 10, (2,2)) #Random Integers
e = np.random.randn(2,3)   #Standard Normal Distribution
print(c)
print(d)
print(e)

[[0.67952846 0.09703978 0.33565036]
 [0.93839205 0.20825234 0.038786  ]]
[[7 7]
 [7 7]]
[[0.0693805  0.34997509 0.80374411]
 [0.36852244 0.22588427 0.08357633]]
[[2 4]
 [1 5]]
[[-1.67521903  0.22664823  1.06668872]
 [ 0.66870645 -0.47307413 -2.69453118]]


In [3]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5)  #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [4]:
arr2 = np.array([[1, 2, 3, 4, 5, 6]])
arr2.shape

(1, 6)

In [5]:
# 2d array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
np.arange(0, 10, 2)  #start, stop, step


array([0, 2, 4, 6, 8])

np.arange() is function from numpy library that creates a sequence of numbers but gives numpy array instead of list or range

arange gives range for numpy array

In [7]:
np.arange(0, 10, 2).reshape(5,1)  #reshape to 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
lspace = np.linspace(1, 5, 12)  #start, stop, number of elements
print(lspace)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


generates equal distance numbers.

In [8]:
np.ones((3, 4))  #3 rows and 4 columns of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((2, 3))  #2 rows and 3 columns of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#identity matrix
np.eye(3)  #3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
a = np.array([1,2,3])
b = a          # same memory
c = a.copy()   # new memory

### Attributes of numpy arrays

In [ ]:


arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr) 
print("Shape:", arr.shape)  #Output: (2, 3)
print("Number of dimensions:", arr.ndim)  #Output: 2
print("Total number of elements:", arr.size)  #Output: 6
print("Data type:", arr.dtype)  #Output: int64 (or int32 depending on the system)
print("Item size (in bytes):", arr.itemsize)  #Output: 8 (or 4 depending on the system)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Total number of elements: 6
Data type: int64
Item size (in bytes): 8


In [40]:
arr = np.arange(99)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [42]:
arr = arr.reshape(3, 33)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [ ]:
arr = arr.ravel()
print(arr)
#retain the original shape of the array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [50]:
ar.ndim

2

In [51]:
ar.size

9

In [52]:
ar.nbytes

72

In [65]:
twod = np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])



In [66]:
twod.argmax()  # gives the index of the maximum value in the array

np.int64(6)

In [67]:
twod.max()  # gives the maximum value in the array

np.int64(7)

In [61]:
twod.argmin()  # gives the index of the minimum value in the array

np.int64(8)

In [68]:
twod.min()  # gives the minimum value in the array

np.int64(0)

In [62]:
twod.argmax(axis = 0)  # gives the indices of the maximum values along the columns

array([2, 1, 1])

In [63]:
twod.argmax(axis = 1)

array([2, 2, 0])

In [64]:
twod.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [72]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
np.count_nonzero(arr)  # counts the number of non-zero elements in the array



[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [73]:
np.where(arr>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))