In [2]:
import numpy as np

### Scalar operations


In [3]:
a = np.array([1,2,3,4,5])

print(a)

print(a+5)
print(a-2)
print(a*2)

[1 2 3 4 5]
[ 6  7  8  9 10]
[-1  0  1  2  3]
[ 2  4  6  8 10]


### Element wise operations

In [4]:
# Numpy Vectorized operations

arr1 = np.array([1,2,3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
print("Addition: ", arr1+arr2)

# Element-wise subtraction
print("Subtraction: ", arr1-arr2)

# Element-wise multiplication
print("Multiplication: ", arr1*arr2)

# Element-wise division
print("Division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


### Comparison operations

In [5]:
a1 = np.arange(10)

print(a1)

print(a1 > 5)
print(a1 == 7)
print(a1 >= 8)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[False False False False False False False  True False False]
[False False False False False False False False  True  True]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.where(arr>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [7]:
# Logical operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data>5  #basically applying condition to our array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
data[data>5]  #this will give us the values that are greater than 5

array([ 6,  7,  8,  9, 10])

In [9]:
data[(data>=5) & (data<=8)]  #this will give us the values that are greater than or equal to 5 and less than or equal to 8

array([5, 6, 7, 8])

### Aggregation operation

In [10]:
a2 = np.arange(1,12)

print(a2)

print(np.sum(a2)) # sum of all elements in array
print(np.prod(a2))
print(np.max(a2))
print(np.min(a2))

[ 1  2  3  4  5  6  7  8  9 10 11]
66
39916800
11
1


### Axis operations

1d array has only one axis i.e axis0

2d array has two axis(axis0, axis1) 

axis1--> (columns)

axis0 ! (rows)

 | 1  2  3 |

 | 4  5  6 |

 | 7  1  9 |

axis0 sum (towards column) = [ 12  8  9 ]

axis1 sum  (towards row)=
 
| 6 |

|15 |
            
| 8 |



In [11]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
ar.sum(axis=0)  #sum of each column

array([12, 15, 18])

In [13]:
ar.sum(axis=1)  #sum of each row

array([ 6, 15, 24])

# Matrix operations


### Round / Floor / Ceil

* Round

Rounds numbers to the nearest value.

* Floor

Floors turns the largest integer less than or equal to the number.

* Ceil

Returns the smallest integer greater than or equal to the number.


In [14]:
import numpy as np
arr = np.array([1.2, 2.6, 3.5, 4.3])

print(np.round(arr))

print()

print(np.floor(arr))

print()

print(np.ceil(arr))

[1. 3. 4. 4.]

[1. 2. 3. 4.]

[2. 3. 4. 5.]


### Transpose

converting rows to columns and column to row

In [15]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
ar = np.array(x)
print(ar)
print(ar.T) #transpose of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
ar.flat # gives iterator

In [17]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


### Dot product

In [18]:


A = np.arange(1,11).reshape(2,5)   # 5 == 5  satisfied
B = np.arange(11,21).reshape(5,2)  # shape 2x2

print(A)
print()
print(B)

dot = np.dot(A,B)

print()
print(dot)
print()

A1 = np.arange(6).reshape(3,2)
B1 = np.arange(6,12).reshape(2,3) # shape 3x3

print(A1)
print()
print(B1)

dot1 = np.dot(A1,B1)
print()
print(dot1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

[[245 260]
 [620 660]]

[[0 1]
 [2 3]
 [4 5]]

[[ 6  7  8]
 [ 9 10 11]]

[[ 9 10 11]
 [39 44 49]
 [69 78 87]]


### Universal functions 

In [19]:
# (ufuncs) --> functions that apply to entire array

arr = np.array([2, 3, 4, 5, 6])

# Square root
print("Square root: ", np.sqrt(arr))

# Exponential
print("Exponential: ", np.exp(arr))

# Logarithm
print("Logarithm: ", np.log(arr))

# sine
print("Sine: ", np.sin(arr))

Square root:  [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Logarithm:  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Sine:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


### Stacking

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print("\n", b , "\n Vertical Stacking")


v_stack = np.vstack((a,b))
print(v_stack)

print("\n Horizontal Stacking ")
h_stack = np.hstack((a,b))
print(h_stack)

[1 2 3]

 [4 5 6] 
 Vertical Stacking
[[1 2 3]
 [4 5 6]]

 Horizontal Stacking 
[1 2 3 4 5 6]


### Splitting



In [21]:
# splitting
c = np.array([1,2,3,4,5,6])
print(np.split(c, 3))

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Vertical Split")
print(np.vsplit(arr, 3))

print("Horizontal Split")   
print(np.hsplit(arr, 3))



[array([1, 2]), array([3, 4]), array([5, 6])]
Vertical Split
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Horizontal Split
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
