## Indexing

Positive Indexing: Move from Left to Right -->> Starts from Zeros

Negative Indexing: move from right to left -->> starts from -1

In [2]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print("\n1D : \n", a1)
print("\n2D : \n", a2)
print("\n3D : \n", a3)


1D : 
 [0 1 2 3 4 5 6 7 8 9]

2D : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
print(a1[0])
print(a1[3])
print(a1[-1])
print()
#2D

print(a2[1,2]) # prints 6
print(a2[2,0]) # 8
print(a2[0,3]) # 3
print(a2[2,3]) # 11

print()
#3D -->> array[layer, row , col]

print(a3[0,1,1]) # 3
print(a3[1,0,0]) # 4
print(a3[1,0,1]) # 5

0
3
9

6
8
3
11

3
4
5


In [20]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array:\n", arr)\
# Accessing a specific element
print("Element at row 1, column 2:", arr[1, 2])

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at row 1, column 2: 7


In [5]:
# Modify array elements
arr[0, 0] = 100
print("Modified array:\n", arr)

Modified array:
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


# Slicing
extracting range of elements from array matrix

#### 1d array

In [ ]:

array = np.array([1, 2, 3, 4, 5])
print("Original array:", array)
# slicing
print("Sliced array (elements from index 1 to 3):", array[1:4]) #inclusive of 1 and exclusive of 4
print("Sliced array (elements from index 2 to end):", array[2:5]) #inclusive of 2 and exclusive of 5
print("Sliced array (elements from start to index 3):", array[0:4]) #inclusive of 0 and exclusive of 4
print("Sliced array (every second element):", array[0:5:2]) #inclusive of 0 and exclusive of 5, with a step of 2

Original array: [1 2 3 4 5]
Sliced array (elements from index 1 to 3): [2 3 4]
Sliced array (elements from index 2 to end): [3 4 5]
Sliced array (elements from start to index 3): [1 2 3 4]
Sliced array (every second element): [1 3 5]


#### 2d array


In [ ]:

print(arr)
print("print starting from index 1 which is second row of 2d array")
print(arr[1:])
print("print excluding last row")
print(arr[:-1]) 


[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
print starting from index 1 which is second row of 2d array
[[ 5  6  7  8]
 [ 9 10 11 12]]
print excluding last row
[[100   2   3   4]
 [  5   6   7   8]]
[[3 4]
 [7 8]]


### Accessing subarrays

In [ ]:

print("Subarray:\n", arr[1:, 2:])

print("Subarray:\n", arr[1: , 1:3])

print("Subarray:\n", arr[0:2 , 2:])

Subarray:
 [[ 7  8]
 [11 12]]


In [24]:
arr[1:] = 100
print("Modified array:\n", arr)

Modified array:
 [[  1   2   3]
 [100 100 100]
 [100 100 100]]


In [33]:

A = np.array([
 [ 1,  2,  3,  4,  5],
 [ 6,  7,  8,  9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]
])
print(A)
print()

print( A[:2, :])
print()
print( A[3:, :])
print()

# Every Second Row
print("Every second row:\n", A[::2, :])
print()

# Every Second Column
print("Every second column:\n", A[:, ::2])
print()

# Extract the Four Corners
print( A[::4, ::4] )
print()


top = A[0, :]
bottom = A[4, :]
left = A[:, 0]
right = A[:, 4]

print(top,left,bottom, right)




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[16 17 18 19 20]
 [21 22 23 24 25]]

Every second row:
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]

Every second column:
 [[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]

[[ 1  5]
 [21 25]]

[1 2 3 4 5] [ 1  6 11 16 21] [21 22 23 24 25] [ 5 10 15 20 25]


#### 3d array

In [31]:
a3 = np.arange(27).reshape(3,3,3)
print("\n3D : \n", a3)

# Extract 2nd 2D array
print( a3[1] )
print()
# Extract 1st and last 2D array

print( a3[::2])
print()

# Extract 2nd row of 1st 2d Array
print( a3[0, 1, :] )
print()

#Extract 2nd col of 2nd 2D 
print( a3[1, :, 1] )
print()

# extraxt 22,23,25,26 from 3rd 2DArray
print( a3[2, 1:, 1:] )
print()

# Extract 0,2 18,20
print( a3[::2, 0, ::2 ])
print()


3D : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[3 4 5]

[10 13 16]

[[22 23]
 [25 26]]

[[ 0  2]
 [18 20]]

