In [ ]:
import numpy as np
a = np.random.randint(1,20, 10) # ranint(start range, end range, nmber of random items)
print(a)
print()
print( a[ [ 0,3,6,8,9] ]) # only prints these indexes 
print( a[ [1,2,9,0] ] )
print( a[[8,0,1,2,3] ] )
print( a[ [ 1,2,3 ] ])



[ 8  8  5  9  1  8 17 18  1 18]

[ 8  9 17  1 18]
[ 8  5 18  8]
[1 8 8 5 9]
[8 5 9]


In [3]:
# 2D
a1 = np.arange(24).reshape(6,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [5]:
# extract 1,2,5,6 rows
print( a1[ [0,1,4,5 ] ])
print()
print(a1[[1,2,5]])
print()

# Extract 0,2,3 cols
print( a1[:,[0,2,3]])
print()
print( a1[:,[1,2]])
print()

print(a1[[0,1,2],[2,1,0]]) #print specific element giving row and col index
print()  # row 0, col2 : row 1 col 1 : row 2 col 0

print(a1[[4,2],[0,1]]) #16 and 9
print()

print( a1[[1,2,5]])
print()
print(a1[:,[1,3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [16 17 18 19]
 [20 21 22 23]]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]]

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]

[2 5 8]

[16  9]

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]]

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]]


# Boolean filtering

Boolean indexing selects elements based on conditions.

          > < >= <= == !=

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])

print(a > 3)
print(a[a > 3])

[False False False  True  True]
[4 5]


In [8]:
a2 = np.random.randint(1,20,8)
print(a2)
print ()
print(a[a>5]) # print elemenst greater than 5
print(a[a==19])
print( a[a<=8] )
print(a[(a>5) & (a%2 == 0)])
print( a[ (a<25) | (a>2)])
print(a[a % 2 == 0])  # even numbers

[14  3 19  6  3 14  1  5]

[ 8  8  9  8 17 18 18]
[]
[8 8 5 1 8 1]
[ 8  8  8 18 18]
[ 8  8  5  9  1  8 17 18  1 18]
[ 8  8  8 18 18]


In [7]:
# 2D
a1 = np.arange(24).reshape(6,4)
print(a1)
print()
print(a1[a1<9])
print(a1[ (a1>= 5 ) & ( a1 <=10 )])
print(a1 [ (a1 >= 6 ) & (a1 % 2 != 0)])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[0 1 2 3 4 5 6 7 8]
[ 5  6  7  8  9 10]
[ 7  9 11 13 15 17 19 21 23]
