# Broadcasting

Broadcasting in NumPy is a smart way of performing operations on arrays of different shapes (sizes) without needing to manually resize them.

Instead of forcing arrays to be the same size, NumPy automatically “stretches” the smaller array so it can match the bigger one during operations like addition, multiplication


Broadcasting Rules (Very Important)

NumPy compares shapes from right to left:

* If dimensions are equal → ✅ OK
* If one dimension is 1 → ✅ Stretch it
* Otherwise → ❌ Error

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = 2

print(a + b)

[3 4 5]


In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [ ]:


a = np.random.randint(1,20, 10) 
print(a)
print()

[ 7  6 13  1  9  6  2 19 13  6]



In [4]:
# 2D + 1D
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print(a + b)

[[2 4 6]
 [5 7 9]]


In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [8]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### Broadcasting with Column

In [5]:
a = np.array([[1],
              [2],
              [3]])

b = np.array([10, 20, 30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


Column + row → creates a full matrix

In [6]:
a = np.array([1, 2, 3])
b = np.array([1, 2])

print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

broadcasting fails because shapes don't match.

In [9]:
a = np.arange(12).reshape(4,3)  
b = np.arange(12).reshape(3,4)  # there is no one to increment and match shape in both

a - b

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [10]:
a = np.arange(3).reshape(1,3)  # ( 1, 3 ) -->> (1->2->3 , 3) -->> (3,3)
b = np.arange(3).reshape(3,1)  # ( 3, 1 ) -->> (3,  1->2->3) --->> (3,3)
#                                  increment the one and match its coresponding nmbrs 

print( a* b )

[[0 0 0]
 [0 1 2]
 [0 2 4]]
