In [2]:
import numpy as np
a = np.arange(12)
a = a.reshape(3,4)
print(a)
a = a.flatten()
print(a)


# stacking
b = np.array([1,2,3])
c = np.array([4,5,6])

print(np.vstack((b,c)))
print(np.hstack((b,c)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


### random and statistics

In [8]:
a = np.random.rand(3)
print(a)
b = np.random.randn(3)
print(b)
c = np.random.randint(1,10,5)
print(c)

# statistics
a = np.array([1,2,3,4,5])
print(np.mean(a))
print(np.std(a))

[0.51550483 0.38815436 0.73999993]
[ 0.55410914  1.08385526 -0.64669568]
[1 7 2 1 4]
3.0
1.4142135623730951


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
np.where(arr>5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [4]:
import sys
py_arr = [0, 4, 55, 2]
np_arr = np.array(py_arr)

In [5]:
sys.getsizeof(1) * len(py_arr)  # size of the list in bytes

112

In [6]:
np_arr.itemsize * np_arr.size  # size of the numpy array in bytes 

32

### Repeat() --- repeat each element

In [7]:
a = np.array([1, 2, 3])

print(np.repeat(a, 3))

[1 1 1 2 2 2 3 3 3]


In [14]:
#2d array
b = np.array([[1, 2],
              [3, 4]])
print(np.repeat(b, 2))

[1 1 2 2 3 3 4 4]


2d becomes 1d

### tile() --- repeat whole array

In [8]:
print(np.tile(a, 3))

[1 2 3 1 2 3 1 2 3]


In [ ]:
#2d array
b = np.array([[1,2],[3,4]])

print(np.tile(b, (2,2)))

[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


### concatenate() --- join/connect arrays

In [9]:
part1 = np.repeat(a, 2)
part2 = np.tile(a, 2)

print(part1)
print(part2)

result = np.concatenate((part1, part2))
print(result)

[1 1 2 2 3 3]
[1 2 3 1 2 3]
[1 1 2 2 3 3 1 2 3 1 2 3]


### stack

In [30]:
a = np.array([1,2])
b = np.array([3,4])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]


### linspace() --- equal spacing

In [16]:
lspace = np.linspace(1, 5, 12)  #start, stop, number of elements
print(lspace)
print(np.linspace(0, 1, 5))

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]
[0.   0.25 0.5  0.75 1.  ]


### where() --- condition finder

In [17]:
a = np.array([1,5,3,8])

print(np.where(a > 4))

(array([1, 3]),)


### sort() --- sort array

In [18]:
a = np.array([3,1,2])
print(np.sort(a))

[1 2 3]


### unique() --- remove duplicates

In [19]:
a = np.array([1,2,2,3])
print(np.unique(a))

[1 2 3]


### clip() --- limit values
np.clip(array, min_value, max_value)

In [29]:
a = np.array([1,5,10])

print(np.clip(a, 2, 8))

[2 5 8]


In [31]:
a = np.array([-5, 0, 5, 10, 15])

print(np.clip(a, 0, 10))

[ 0  0  5 10 10]


In [ ]:
#2d array
a = np.array([[1, 20],
              [5, -3]])

print(np.clip(a, 0, 10))

[[ 1 10]
 [ 5  0]]


### abs() --- gives positive integers

In [33]:


a = np.array([-5, -2, 0, 3, 7])

print(np.abs(a))

[5 2 0 3 7]


In [34]:
#2d array
a = np.array([[-1, 2],
              [-3, 4]])

print(np.abs(a))

[[1 2]
 [3 4]]


### greater smaller elements

In [20]:
one = np.array([1, 3, 4, 634, 2])
one.argmax()  #gives the index of the maximum value in the array

np.int64(3)

In [23]:
one.max()  #gives the maximum value in the array

np.int64(634)

In [21]:
one.argmin()  #gives the index of the minimum value in the array

np.int64(0)

In [24]:
one.min()  #gives the minimum value in the array

np.int64(1)

In [22]:
one.argsort()  #gives the indices that would sort the array

array([0, 4, 1, 2, 3])

In [28]:
one.sort()  #sorts the array in place
print(one)

[  1   2   3   4 634]


📦 Creation

* arange, linspace
🔧 Shape

* reshape, flatten

➕ Math

* sum, mean, max

🔍 Logic

* where, boolean filtering

🔗 Combine

* concatenate, vstack

🎲 Random

* randint

### np.random.seed() --- control randomness
Normally, random numbers change every time you run code.

👉 seed() makes them repeatable (same output every run)

In [36]:
# example without seed()
import numpy as np

print(np.random.randint(1, 10, 5)) # output changes every time

[9 2 1 8 3]


In [39]:
np.random.seed(1)
print(np.random.randint(1, 10, 5))

[6 9 6 1 1]


seed() = “freeze randomness”

### np.percentile() → find position value
It tells you:

“At this percentage, what value lies here?”

In [40]:
a = np.array([10, 20, 30, 40, 50])

print(np.percentile(a, 50))

30.0


In [41]:
print(np.percentile(a, 0))    # minimum
print(np.percentile(a, 25))   # lower quarter
print(np.percentile(a, 75))   # upper quarter
print(np.percentile(a, 100))  # maximum

10.0
20.0
40.0
50.0


### cumsum() --- commulative sum


In [42]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(np.cumsum(a))

[ 1  3  6 10]


How it works:
* 1 → 1
* 1+2 → 3
* 1+2+3 → 6
* 1+2+3+4 → 10

In [43]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(np.cumsum(a))

[ 1  3  6 10 15 21]


In [ ]:
print(np.cumsum(a, axis=1)) #row wise cumulative sum

[[ 1  3  6]
 [ 4  9 15]]


In [45]:
print(np.cumsum(a, axis=0)) #column wise cumulative sum

[[1 2 3]
 [5 7 9]]


### flip()

In [46]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Original:\n", arr)

# Flip both axes
flipped = np.flip(arr)
print("\nFlipped along both axes:\n", flipped)

Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped along both axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
