In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("First array:")
print(a)
print()
print("Second array:")
print(b)
print()
print("Dot product of a and b:")
print(np.dot(a,b))
print()
print("Transpose of a:")
print(a.T) 
print()
print("Transpose of b:")
print(b.T)
print()
print("Dot product of b and a:")
print(np.dot(b,a))
print()
print("Logarithm of a:")
print(np.log(a))
print()
print("Exponential of b:")
print(np.exp(b))
print()
print("Ceiling of a:")
print(np.ceil(a))
print()
print("Floor of b:")
print(np.floor(b))
print()
print("Rounded a:")
print(np.round(a))
print()
print("Flattened a:")
print(np.ravel(a))
print()
print("Flattened b:")
print(np.ravel(b))
print()


First array:
[[1 2]
 [3 4]]

Second array:
[[5 6]
 [7 8]]

Dot product of a and b:
[[19 22]
 [43 50]]

Transpose of a:
[[1 3]
 [2 4]]

Transpose of b:
[[5 7]
 [6 8]]

Dot product of b and a:
[[23 34]
 [31 46]]

Logarithm of a:
[[0.         0.69314718]
 [1.09861229 1.38629436]]

Exponential of b:
[[ 148.4131591   403.42879349]
 [1096.63315843 2980.95798704]]

Ceiling of a:
[[1 2]
 [3 4]]

Floor of b:
[[5 6]
 [7 8]]

Rounded a:
[[1 2]
 [3 4]]

Flattened a:
[1 2 3 4]

Flattened b:
[5 6 7 8]



In [8]:
# Q-1 Create a null vector of size 10 but the fifth value which is 1.
null=np.zeros((2,5))
print(null)
null[0][4]=1
print(null)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [9]:
# Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.
a=int(input("Enter the  number of rows: "))
b=int(input("Enter the number of columns: "))
c=np.random.randint((a,b))
print(c)

[1 0]


In [10]:
# Q-3 Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.
# Eg.-

# [[1,1,1,1],
# [1,0,0,1],
# [1,0,0,1],
# [1,1,1,1]]

a=int(input("Enter the  number of rows: "))
b=int(input("Enter the number of columns: "))
c=np.full((a,b),0)
c[[0,-1]]=1
c[: ,[0,-1]]=1
print(c)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [11]:
# Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.
a=np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [12]:
# Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it. No
a=np.eye(3, 4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [14]:
# Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.
import numpy as np
a = np.arange(5)
a = np.repeat(a.reshape(1,5), 5, axis=0)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [15]:
#second way   
a = np.tile(np.arange(5), (5,1)) #(rep, axis)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [16]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


In [17]:
# You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.
# Input Format:
# A single line of input containing space separated numbers.
# Output Format:
# Print the reverse NumPy array with type float.
# Example 1:
# Input:
# 1 2 3 4 -8 -10
# Output:
# [-10.  -8.   4.   3.   2.   1.]

import numpy as np

a = "1 2 3 4 -8 -10".split()

arr = np.array(a, float)

print(arr[::-1])

[-10.  -8.   4.   3.   2.   1.]


In [18]:
# Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, 
# otherwise raise error. The date format should be like this only: 2022-12-6. 
# The end date should be included and for simplicity, choose dates from a same year.

# Example 1:

# Input:

# date_array(start = '2020-09-15', end = '2020-09-25')
# Output:

# ['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
#  '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
#  '2020-09-23', '2020-09-24', '2020-09-25']
import numpy as np

def date_array(start, end):

    # type checking
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("Both inputs must be strings")

    start_date = np.datetime64(start)
    end_date = np.datetime64(end)

    # include end date
    dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'))

    return dates

print(date_array('2020-09-15', '2020-09-25'))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


In [21]:
#  Subtract the mean of each row from a matrix.
a = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
mean=np.mean(a, axis=1, keepdims=True)
print(a-mean)

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


In [22]:
# Swap column-1 of array with column-2 in the array.
import numpy as np

a = np.array([[0,1,2,3,4]])

# swap column 1 and column 2
a[:, [1,2]] = a[:, [2,1]]

print(a)

[[0 2 1 3 4]]


In [23]:
# Replace odd elements in arrays with -1.

a = np.array([0,1,2,3,4])
a[a%2!=0]=-1
print(a)

[ 0 -1  2 -1  4]


In [25]:
#Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
#element wise comparison

a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
np.maximum(a,b) #max is used for max of an array and maximum for element wise comparison

array([6, 3, 1, 7, 8])

In [26]:
# Fetch Every alternate column of the array
# Normalise the given array
import numpy as np

# given array
arr1 = np.random.randint(low=1, high=10000, size=40).reshape(8,5)

print("Original Array:\n", arr1)

#Fetch every alternate column
alternate_columns = arr1[:, ::2]
print("\nAlternate Columns:\n", alternate_columns)

#Normalize the array
xmin = np.min(arr1)
xmax = np.max(arr1)

normalized_array = (arr1 - xmin) / (xmax - xmin)

print("\nNormalized Array:\n", normalized_array)

Original Array:
 [[3001 9731 7181 9439 6098]
 [1562 1553 1801 8794 1997]
 [ 502 6278 3105  456 4555]
 [5877 5794 7882 8283 3854]
 [1748 6139 7588 8596 8825]
 [3723 7015 1031 9335 6958]
 [9228 3279 6966 5895 7022]
 [4426 5257 4037 1282 2888]]

Alternate Columns:
 [[3001 7181 6098]
 [1562 1801 1997]
 [ 502 3105 4555]
 [5877 7882 3854]
 [1748 7588 8825]
 [3723 1031 6958]
 [9228 6966 7022]
 [4426 4037 2888]]

Normalized Array:
 [[0.27439353 1.         0.72506739 0.96851752 0.60830189]
 [0.11924528 0.11827493 0.14501348 0.89897574 0.16614555]
 [0.00495957 0.62770889 0.28560647 0.         0.4419407 ]
 [0.58447439 0.57552561 0.8006469  0.8438814  0.36636119]
 [0.13929919 0.61272237 0.76894879 0.87762803 0.90231806]
 [0.3522372  0.70716981 0.06199461 0.95730458 0.70102426]
 [0.94576819 0.30436658 0.70188679 0.58641509 0.70792453]
 [0.42803235 0.51762803 0.38609164 0.0890566  0.26221024]]


In [27]:
# Write a function which will accept 2 arguments.
# First: A 1D numpy array arr

# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be

import numpy as np

def find_value(arr, n):
    if n > len(arr):
        print("n should be <=", len(arr))
        return None
    
    arr_sorted = np.sort(arr)[::-1]   # sort descending
    return arr_sorted[n-1]


a = np.array([12,34,40,7,1,0])
result = find_value(a,3)

print(result)

12


In [ ]:
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
import numpy as np
a = np.array([1,2,3])
part1 = np.repeat(a,3)
part2 = np.tile(a,3)
result = np.concatenate((part1, part2))
print(result)

In [28]:
# Replace multiples of 3 or 5 as 0 in the given array.
# arr=[1 2 3 4 5 6 7 9]

# result-> [1 2 0 4 0 0 7 0]
a=np.array([1,2,3,4,5,6,7,9])
a[(a%5==0) | (a%3==0)]=0
print(a)

[1 2 0 4 0 0 7 0]


In [3]:
# Find the nearest element in the array to a given integer.
# Ex:- 
# a=23 and array - [10 17 24 31 38 45 52 59].
# Nearest element is 24
# Hint: Read about this function argmin()
a = np.array([10, 17, 24, 31, 38, 45, 52, 59])
abs_difference=np.abs(a-23)
index=abs_difference.argmin()
print(index)

2


In [4]:
#Write a program implement Boradcasting Rule to check if two array can be added or not.
# Given tuples of shapes.

# shape of a- (3,2,2)
# shape of b- (2,2)

def can_broadcast(shape_a, shape_b):

    a = list(shape_a[::-1])
    b = list(shape_b[::-1])

    for i in range(max(len(a), len(b))):
        
        dim_a = a[i] if i < len(a) else 1
        dim_b = b[i] if i < len(b) else 1

        if dim_a != dim_b and dim_a != 1 and dim_b != 1:
            return False

    return True


shape_a = (3,2,2)
shape_b = (2,2)

print("Broadcast possible:", can_broadcast(shape_a, shape_b))

Broadcast possible: True
